name: Deploy Allure Report

on:
  workflow_run:
    workflows: ["Run Tests"]  # Запускать после завершения workflow "Run Tests"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          keep_files: true