name: Run Tests

on:
  workflow_dispatch:  # Ручной запуск
    inputs:
      browser:
        description: "Выберите браузер (chrome, firefox или all)"
        required: true
        default: "all"
        type: choice
        options:
          - chrome
          - firefox
          - all
  push:
    branches:
      - main  # Запускать тесты только при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать тесты при создании пул-реквеста в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    needs: selenium-grid-setup  # Зависит от workflow "Selenium Grid Setup"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install default-jre -y
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -xzf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Determine browser
        id: browser
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Выбран браузер: ${{ github.event.inputs.browser }}"
            echo "browser=${{ github.event.inputs.browser }}" >> $GITHUB_ENV
          else
            echo "Запуск по умолчанию: все браузеры"
            echo "browser=all" >> $GITHUB_ENV
          fi

      - name: Run tests
        continue-on-error: true
        run: |
          if [ "$browser" == "all" ]; then
            pytest tests/ --alluredir=allure-results --maxfail=10
          else
            pytest tests/ --browser=$browser --alluredir=allure-results --maxfail=10
          fi

      - name: Generate Allure report
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results -o allure-report --clean
          else
            echo "No test results found. Skipping Allure report generation."
          fi

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results