name: Run Tests with Docker

on:
  workflow_dispatch:  # Ручной запуск
  push:
    branches:
      - main  # Запускать тесты только при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать тесты при создании пул-реквеста в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo docker --version  # Проверяем установку Docker

      # Шаг 3: Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -t automation-qa .

      # Шаг 4: Запускаем тесты в Docker-контейнере
      - name: Run tests in Docker
        continue-on-error: true  # Продолжать выполнение, даже если тесты упали
        run: |
          docker run -v $(pwd)/allure-results:/app/allure-results automation-qa

      # Шаг 5: Устанавливаем Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install default-jre -y
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -xzf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version  # Проверяем установку

      # Шаг 6: Генерируем Allure-отчет
      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean

      # Шаг 7: Загружаем Allure-отчет как артефакт
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      # Шаг 8: Загружаем результаты Allure-results как артефакт (для отладки)
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # Шаг 9: Публикуем отчет на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          keep_files: true  # Сохранять существующие файлы в ветке gh-pages